name: Deploy Angular App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0
          
      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/**/browser/*"
          target: "/tmp/angular-deploy"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /tmp/angular-deploy/* /usr/share/nginx/html/
            sudo chown -R nginx:nginx /usr/share/nginx/html
            sudo systemctl restart nginx
